### ISSUE TITLE
missing database

### ISSUE THREAD

**Issue by shawngraham** [DocNow/dnflow-ansible#10]
HI,

The search feature wasn't working at all. PUzzling through it with Ed, it seems as if the database wasn't formed correctly (vagrant, on a Mac). There was no data directory created:

```
vagrant@vagrant-ubuntu-trusty-64:/home/docnow/dnflow$ ls
db.sqlite3           __init__.py  queue_tasks.py    static
dnflow.cfg           LICENSE      README.md         summarize.py
dnflow.cfg.template  luigi.cfg    requirements.txt  templates
docnow.ini           __pycache__  schema.sql        ui.py
```

I `cd /home/docnow/dnflow` and then `sqlite3 db.sqlite3` with the result:
`sqlite> SELECT * FROM searches;
Error: no such table: searches`

so we:

`sudo -u docnow -s ; sqlite3 db.sqlite3 < schema.sql`

but I had to re-enter the `sqlite3 db.sqlite3 < schema.sql` to get it to take. And then the search in the webapp performed as expected.

**Comment by ianmilligan1** [comment]
Followed above steps (getting into vagrant via `vagrant ssh`), but while search populates it does nothing and just hangs there..
![screen shot 2016-08-31 at 11 48 51 am](https://cloud.githubusercontent.com/assets/3834704/18135747/ee1529e2-6f70-11e6-81fb-b721e79c1812.png)

**Comment by kayiwa** [comment]
Hey @ianmilligan1 can you post the contents of `/var/log/uwsgi/docnow.log` when you have a moment? 

Cheers

**Comment by ianmilligan1** [comment]
Certainly – [I've gist'ed it here](https://gist.github.com/ianmilligan1/c88bc6f736aa9f14660ab3a7a644bba1). Thanks for your help and hope this is helpful!
