### ISSUE TITLE
Search input not registering search

### ISSUE THREAD

**Issue by ianmilligan1** [DocNow/dnflow-ansible#12]
I've been trying to get this up and running locally. However, I can get to this stage, logged in and authenticated in Twitter:
![screen shot 2016-08-31 at 11 14 50 am](https://cloud.githubusercontent.com/assets/3834704/18134405/4488c37e-6f6c-11e6-809d-5cf8cd8d86c8.png)
But if I enter a query and click 'add,' nothing happens. 

What kind of information would you like to see where I've gone wrong?

**Comment by edsu** [comment]
@kayiwa if you are working on this @shawngraham and I tracked this down to the sqlite database not being created. 

See also #10

**Comment by ianmilligan1** [comment]
Ah, I hadn't realized the answer was in the question there. Let me give it a try!

**Comment by ianmilligan1** [comment]
Closing, as issue is covered in #10.
