### ISSUE TITLE
Vagrant Build failing on AWS

### ISSUE THREAD

**Issue by ianmilligan1** [DocNow/dnflow-ansible#14]
Hi folks –

I've been trying to get this deployed on AWS for longer than I'm willing to admit now (I'll hopefully push some tweaks to your README.md file). But I'm finally hitting the wall here on an issue related to #8.

Build fails on AWS with:

```
TASK [remove nginx default virtual host] ***************************************
changed: [default]

TASK [copy nginx virtualhost] **************************************************
fatal: [default]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: {{ ansible_eth1.ipv4.address }}: 'ansible_eth1' is undefined"}
	to retry, use: --limit @/vagrant/docnow.retry

PLAY RECAP *********************************************************************
default                    : ok=23   changed=20   unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

My `group_vars/all` is as follows, with keys removed but everything else the same:

```

---
hostname: "{{ ansible_eth1.ipv4.address }}"
twitter_consumer_key: JSp5BzLifNopFcmPdpzKcYSUC
twitter_consumer_secret: bNwef7erMVbdmj8fDNW6kuVgyoYBCJpeWWsd1zMo4ruyc5nH1Q
http_basicauth_user:
http_basicauth_pass:
#google_analytics: blah
```

I know the problem is in there somewhere.. Thanks all.

**Comment by ianmilligan1** [comment]
I should note that I have also run `group_vars/all` as

```
---
hostname: "{{ ansible_eth1.ipv4.address }}"
twitter_consumer_key: JSp5BzLifNopFcmPdpzKcYSUC
twitter_consumer_secret: bNwef7erMVbdmj8fDNW6kuVgyoYBCJpeWWsd1zMo4ruyc5nH1Q
#http_basicauth_user:
#http_basicauth_pass:
#google_analytics: blah
```

**Comment by ianmilligan1** [comment]
Might have resolved it with:

```
---
hostname: "{{ ansible_default_ipv4.address }}"
```

and then providing Twitter credentials.

In `Vagrantfile` added

```
ansible.extra_vars = { google_analytics: false }
```

Under `config.vm.provision :ansible_local do |ansible|`. Will keep you posted..

**Comment by kayiwa** [comment]
hey @ianmilligan1 I've been _mostly_ off grid and can give this a proper look tomorrow afternoon/evening. Apologies.

**Comment by ianmilligan1** [comment]
Hah not a problem at all. None of this is time sensitive, so enjoy your time off grid. 😃

**Comment by ianmilligan1** [comment]
BTW, I am putting my workflow here in case this helps:

https://github.com/ianmilligan1/AHA-Workshop/blob/master/DocNow/README.md

If you're open to pull requests, I'm happy to tweak some of the README on your repo too just to reflect more newbie language.

**Comment by kayiwa** [comment]
Hey @ianmilligan1 we gladly welcome pull requests. Thanking you in advance.
