### ISSUE TITLE
rq worker fails

### ISSUE THREAD

**Issue by edsu** [DocNow/dnflow-ansible#2]
`rq worker` throws an exception when pulling search jobs off the queue.

```
'module' object has no attribute 'run'
```

**Comment by edsu** [comment]
@kayiwa when you get a chance please give this branch a try. It seems to work for me. Just be sure to follow the instructions about adding `TWITTER_CONSUMER_KEY` and `TWITTER_CONSUMER_SECRET` to `group_vars/all`

**Comment by kayiwa** [comment]
This worked for me. Thanks for this!

**Comment by edsu** [comment]
Awesome, thanks for checking it @kayiwa
