### ISSUE TITLE
remove redis configuration

### ISSUE THREAD

**Issue by edsu** [DocNow/dnflow-ansible#4]
It doesn't look like `redis.yml` is used anymore -- since it's covered in `docnow`. Can it be removed to keep things simple?

**Comment by kayiwa** [comment]
removed it with this commit https://github.com/DocNow/dnflow-ansible/commit/0da648820fd8ed66bf21cf8d76e5c135d4af700e

**Comment by edsu** [comment]
But the (unused) redis directory is still there?
