### ISSUE TITLE
config issue maybe?

### ISSUE THREAD

**Issue by shawngraham** [DocNow/dnflow-ansible#8]
Hi folks,

I get to this:

``` bash
TASK [copy nginx virtualhost] **************************************************
fatal: [default]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'http_basicauth_user' is undefined"}

NO MORE HOSTS LEFT *************************************************************
 [WARNING]: Could not create retry file 'docnow.retry'.         [Errno 2] No
such file or directory: ''

```

my 'all' file:

hostname: "{{ ansible_eth0.ipv4.address }}"
twitter_consumer_key:   <mykeyenteredhere>
twitter_consumer_secret: <mysecretenteredhere>
# http_basicauth_user:
# http_basicauth_pass:

... I'm missing something quite basic, right?

**Comment by kayiwa** [comment]
Hey @shawngraham could you please post the contents of `group_vars/all` here. Ooops. I see you did. Can you uncheck the commented http_basic_auth_user and the http_basic_auth_pass please. 

Cheers

**Comment by shawngraham** [comment]
oh gosh. Man, couldn't see for looking. thanks!
