### ISSUE TITLE
oauth

### ISSUE THREAD

**Issue by shawngraham** [DocNow/dnflow-ansible#9]
Hi folks,

Me again. When the app goes to login to twitter, the callback for the authentication is to:

http://10.0.2.15/oauth-authorized?next=http%3A%2F%2F192.168.60.14%2F&oauth_token= [etc] &oauth_verifier= [etc]

? and nothing else occurs.

**Comment by kayiwa** [comment]
heya,

I will add this to the README. Change your `{{ ansible_eth0.ipv4.address }}` to say hostname: "{{ ansible_eth1.ipv4.address }}"

or

`vagrant ssh`

and you will need to change the following

/home/docnow/dnflow/dnflow.cfg to 192.168.60.14

/home/docnow/dnflow/dnflow.cfg  to 192.168.60.14

Cheers

**Comment by shawngraham** [comment]
ok, great; changing it to `ansible_eth1` etc seems to have gotten the authentication to work. And now to see what happens next! Thank you very much for your patience with me.
